//
// DISCLAIMER
//
// Copyright 2022 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: deploymentprofile.proto

package v1

import (
	context "context"
	v1 "github.com/arangodb-managed/apis/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeploymentProfileService_GetAPIVersion_FullMethodName          = "/arangodb.cloud.deploymentprofile.v1.DeploymentProfileService/GetAPIVersion"
	DeploymentProfileService_ListDeploymentProfiles_FullMethodName = "/arangodb.cloud.deploymentprofile.v1.DeploymentProfileService/ListDeploymentProfiles"
)

// DeploymentProfileServiceClient is the client API for DeploymentProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Deployment Profile service is used to manage Deployment Profiles.
type DeploymentProfileServiceClient interface {
	// Get the current API version of this service.
	// Required permissions:
	// - None (authenticated only)
	GetAPIVersion(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.Version, error)
	// List all deployment profiles for the organization identified by the given organization identifier.
	// Required permissions:
	// - deploymentprofile.deploymentprofile.list on the organization
	ListDeploymentProfiles(ctx context.Context, in *ListDeploymentProfilesRequest, opts ...grpc.CallOption) (*DeploymentProfileList, error)
}

type deploymentProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentProfileServiceClient(cc grpc.ClientConnInterface) DeploymentProfileServiceClient {
	return &deploymentProfileServiceClient{cc}
}

func (c *deploymentProfileServiceClient) GetAPIVersion(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.Version, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Version)
	err := c.cc.Invoke(ctx, DeploymentProfileService_GetAPIVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentProfileServiceClient) ListDeploymentProfiles(ctx context.Context, in *ListDeploymentProfilesRequest, opts ...grpc.CallOption) (*DeploymentProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentProfileList)
	err := c.cc.Invoke(ctx, DeploymentProfileService_ListDeploymentProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentProfileServiceServer is the server API for DeploymentProfileService service.
// All implementations must embed UnimplementedDeploymentProfileServiceServer
// for forward compatibility.
//
// Deployment Profile service is used to manage Deployment Profiles.
type DeploymentProfileServiceServer interface {
	// Get the current API version of this service.
	// Required permissions:
	// - None (authenticated only)
	GetAPIVersion(context.Context, *v1.Empty) (*v1.Version, error)
	// List all deployment profiles for the organization identified by the given organization identifier.
	// Required permissions:
	// - deploymentprofile.deploymentprofile.list on the organization
	ListDeploymentProfiles(context.Context, *ListDeploymentProfilesRequest) (*DeploymentProfileList, error)
	mustEmbedUnimplementedDeploymentProfileServiceServer()
}

// UnimplementedDeploymentProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentProfileServiceServer struct{}

func (UnimplementedDeploymentProfileServiceServer) GetAPIVersion(context.Context, *v1.Empty) (*v1.Version, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPIVersion not implemented")
}
func (UnimplementedDeploymentProfileServiceServer) ListDeploymentProfiles(context.Context, *ListDeploymentProfilesRequest) (*DeploymentProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeploymentProfiles not implemented")
}
func (UnimplementedDeploymentProfileServiceServer) mustEmbedUnimplementedDeploymentProfileServiceServer() {
}
func (UnimplementedDeploymentProfileServiceServer) testEmbeddedByValue() {}

// UnsafeDeploymentProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentProfileServiceServer will
// result in compilation errors.
type UnsafeDeploymentProfileServiceServer interface {
	mustEmbedUnimplementedDeploymentProfileServiceServer()
}

func RegisterDeploymentProfileServiceServer(s grpc.ServiceRegistrar, srv DeploymentProfileServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeploymentProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploymentProfileService_ServiceDesc, srv)
}

func _DeploymentProfileService_GetAPIVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentProfileServiceServer).GetAPIVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentProfileService_GetAPIVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentProfileServiceServer).GetAPIVersion(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentProfileService_ListDeploymentProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentProfileServiceServer).ListDeploymentProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentProfileService_ListDeploymentProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentProfileServiceServer).ListDeploymentProfiles(ctx, req.(*ListDeploymentProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploymentProfileService_ServiceDesc is the grpc.ServiceDesc for DeploymentProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arangodb.cloud.deploymentprofile.v1.DeploymentProfileService",
	HandlerType: (*DeploymentProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAPIVersion",
			Handler:    _DeploymentProfileService_GetAPIVersion_Handler,
		},
		{
			MethodName: "ListDeploymentProfiles",
			Handler:    _DeploymentProfileService_ListDeploymentProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deploymentprofile.proto",
}
