version: 2.1
executors:
  go-executor:
    docker:
      - image: arangodboasis/golang-ci:latest
jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          make check-version # fail early if there is a version inconsistency
          make all
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: gcr
          filters:
            tags:
              only: /.*/
